# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StatOp.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_statWindow(object):
    def setupUi(self, statWindow, statCtrl):
        statWindow.setObjectName("statWindow")
        statWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        statWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(statWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 40, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.displayEnrolledBut = QtWidgets.QPushButton(self.centralwidget)
        self.displayEnrolledBut.setGeometry(QtCore.QRect(100, 160, 160, 81))
        self.displayEnrolledBut.setText("")
        self.displayEnrolledBut.setObjectName("displayEnrolledBut")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 170, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.DisplayFailingBut = QtWidgets.QPushButton(self.centralwidget)
        self.DisplayFailingBut.setGeometry(QtCore.QRect(100, 250, 160, 81))
        self.DisplayFailingBut.setText("")
        self.DisplayFailingBut.setObjectName("DisplayFailingBut")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 260, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.RankingBut = QtWidgets.QPushButton(self.centralwidget)
        self.RankingBut.setGeometry(QtCore.QRect(100, 340, 160, 81))
        self.RankingBut.setText("")
        self.RankingBut.setObjectName("RankingBut")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 360, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.ActiveDisciBut = QtWidgets.QPushButton(self.centralwidget)
        self.ActiveDisciBut.setGeometry(QtCore.QRect(100, 430, 160, 81))
        self.ActiveDisciBut.setText("")
        self.ActiveDisciBut.setObjectName("ActiveDisciBut")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 450, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.Browser = QtWidgets.QTextBrowser(self.centralwidget)
        self.Browser.setGeometry(QtCore.QRect(320, 160, 431, 341))
        self.Browser.setObjectName("Browser")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(280, 160, 20, 341))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        statWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(statWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        statWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(statWindow)
        self.statusbar.setObjectName("statusbar")
        statWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(statWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuExit.addAction(self.actionExit)
        self.menubar.addAction(self.menuExit.menuAction())

        self.retranslateUi(statWindow)
        QtCore.QMetaObject.connectSlotsByName(statWindow)

    def retranslateUi(self, statWindow):
        _translate = QtCore.QCoreApplication.translate
        statWindow.setWindowTitle(_translate("statWindow", "Statistics"))
        self.label.setText(_translate("statWindow", "Statistics Operations"))
        self.label_2.setText(_translate("statWindow", "Display students enrolled at a given discipline"))
        self.label_3.setText(_translate("statWindow", "Display failing students"))
        self.label_4.setText(_translate("statWindow", "Ranking"))
        self.label_5.setText(_translate("statWindow", "Active disciplines"))
        self.menuExit.setTitle(_translate("statWindow", "File"))
        self.actionExit.setText(_translate("statWindow", "Exit"))

